### ISSUE TITLE
Retrofit impact failed downloading small area boundaries

### ISSUE THREAD

**Issue by john-oshea** [codema-dev/projects#124]
```
/srv/conda/envs/notebook/lib/python3.7/site-packages/ploomber/dag/dag.py:390: UserWarning: 
=========================== DAG render with warnings ===========================
- NotebookRunner: plot_retrofit_costs -> MetaProduct({'nb': File('data/no..._costs.ipynb')}) -
- /home/jovyan/projects/estimate-retrofit-impact-on-heat-pump-viability/plot_retrofit_costs.py -
:1:1 'geopandas as gpd' imported but unused
- NotebookRunner: plot_energy_savings -> MetaProduct({'nb': File('data/no...avings.ipynb')}) -
- /home/jovyan/projects/estimate-retrofit-impact-on-heat-pump-viability/plot_energy_savings.py -
:1:1 'geopandas as gpd' imported but unused
- NotebookRunner: plot_pre_vs_post_retrofit_bers -> MetaProduct({'nb': File('data/no...t_bers.ipynb')}) -
- /home/jovyan/projects/estimate-retrofit-impact-on-heat-pump-viability/plot_pre_vs_post_retrofit_bers.py -
:1:1 'geopandas as gpd' imported but unused
============================== Summary (3 tasks) ===============================
NotebookRunner: plot_retrofit_costs -> MetaProduct({'nb': File('data/no..._costs.ipynb')})
NotebookRunner: plot_energy_savings -> MetaProduct({'nb': File('data/no...avings.ipynb')})
NotebookRunner: plot_pre_vs_post_retrofit_bers -> MetaProduct({'nb': File('data/no...t_bers.ipynb')})
=========================== DAG render with warnings ===========================

  warnings.warn(str(warnings_))
Building task 'plot_uvalue_distribution':  23%|▍ | 3/13 [00:26<01:53, 11.34s/it]
Executing:   0%|                                       | 0/12 [00:00<?, ?cell/s]
Executing:   8%|██▌                            | 1/12 [00:01<00:17,  1.58s/cell]
Executing:  17%|█████▏                         | 2/12 [00:02<00:14,  1.42s/cell]
Executing:  33%|██████████▎                    | 4/12 [00:03<00:04,  1.72cell/s]
Executing:  50%|███████████████▌               | 6/12 [00:09<00:10,  1.80s/cell]
Executing:  58%|██████████████████             | 7/12 [00:09<00:07,  1.47s/cell]
Executing:  67%|████████████████████▋          | 8/12 [00:10<00:04,  1.22s/cell]
Executing:  75%|███████████████████████▎       | 9/12 [00:10<00:03,  1.00s/cell]
Executing:  83%|█████████████████████████     | 10/12 [00:11<00:01,  1.00cell/s]
Executing:  92%|███████████████████████████▌  | 11/12 [00:12<00:00,  1.03cell/s]
Executing: 100%|██████████████████████████████| 12/12 [00:14<00:00,  1.18s/cell]
Building task 'plot_retrofit_costs':  62%|████▎  | 8/13 [02:08<01:44, 20.84s/it]
Executing:   0%|                                       | 0/17 [00:00<?, ?cell/s]
Executing:   6%|█▊                             | 1/17 [00:02<00:39,  2.44s/cell]
Executing:  12%|███▋                           | 2/17 [00:03<00:22,  1.51s/cell]
Executing:  24%|███████▎                       | 4/17 [00:03<00:07,  1.63cell/s]
Executing:  35%|██████████▉                    | 6/17 [00:03<00:03,  2.76cell/s]
Executing:  41%|████████████▊                  | 7/17 [00:09<00:16,  1.67s/cell]
Executing:  47%|██████████████▌                | 8/17 [00:09<00:11,  1.31s/cell]
Executing:  53%|████████████████▍              | 9/17 [00:09<00:07,  1.03cell/s]
Executing:  59%|█████████████████▋            | 10/17 [00:09<00:05,  1.37cell/s]
Executing:  65%|███████████████████▍          | 11/17 [00:09<00:03,  1.77cell/s]
Executing:  71%|█████████████████████▏        | 12/17 [00:10<00:02,  2.22cell/s]
Executing:  76%|██████████████████████▉       | 13/17 [00:10<00:01,  2.80cell/s]
Executing:  82%|████████████████████████▋     | 14/17 [00:10<00:00,  3.47cell/s]
Executing:  88%|██████████████████████████▍   | 15/17 [00:10<00:00,  4.23cell/s]
Executing:  94%|████████████████████████████▏ | 16/17 [00:10<00:00,  4.76cell/s]
Executing: 100%|██████████████████████████████| 17/17 [00:11<00:00,  1.52cell/s]
Building task 'plot_energy_savings':  77%|████▌ | 10/13 [02:54<01:09, 23.25s/it]
Executing:   0%|                                       | 0/26 [00:00<?, ?cell/s]
Executing:   4%|█▏                             | 1/26 [00:02<01:05,  2.60s/cell]
Executing:   8%|██▍                            | 2/26 [00:03<00:36,  1.52s/cell]
Executing:  12%|███▌                           | 3/26 [00:03<00:20,  1.14cell/s]
Executing:  15%|████▊                          | 4/26 [00:03<00:12,  1.73cell/s]
Executing:  19%|█████▉                         | 5/26 [00:03<00:08,  2.40cell/s]
Executing:  23%|███████▏                       | 6/26 [00:03<00:06,  3.23cell/s]
Executing:  27%|████████▎                      | 7/26 [00:09<00:39,  2.08s/cell]
Executing:  31%|█████████▌                     | 8/26 [00:14<00:55,  3.09s/cell]
Executing:  35%|██████████▋                    | 9/26 [00:19<01:01,  3.60s/cell]
Executing:  38%|███████████▌                  | 10/26 [00:19<00:40,  2.52s/cell]
Executing:  42%|████████████▋                 | 11/26 [00:19<00:27,  1.80s/cell]
Executing:  46%|█████████████▊                | 12/26 [00:19<00:18,  1.29s/cell]
Executing:  50%|███████████████               | 13/26 [00:20<00:12,  1.06cell/s]
Executing:  54%|████████████████▏             | 14/26 [00:20<00:08,  1.42cell/s]
Executing:  58%|█████████████████▎            | 15/26 [00:20<00:05,  1.89cell/s]
Executing:  62%|██████████████████▍           | 16/26 [00:20<00:04,  2.44cell/s]
Executing:  65%|███████████████████▌          | 17/26 [00:20<00:02,  3.11cell/s]
Executing:  69%|████████████████████▊         | 18/26 [00:20<00:02,  3.83cell/s]
Executing:  73%|█████████████████████▉        | 19/26 [00:20<00:01,  4.54cell/s]
Executing:  77%|███████████████████████       | 20/26 [00:20<00:01,  5.18cell/s]
Executing:  81%|████████████████████████▏     | 21/26 [00:21<00:01,  4.75cell/s]
Executing:  85%|█████████████████████████▍    | 22/26 [00:21<00:00,  5.30cell/s]
Executing:  88%|██████████████████████████▌   | 23/26 [00:21<00:00,  5.74cell/s]
Executing:  92%|███████████████████████████▋  | 24/26 [00:21<00:00,  5.19cell/s]
Executing:  96%|████████████████████████████▊ | 25/26 [00:21<00:00,  5.52cell/s]
Executing: 100%|██████████████████████████████| 26/26 [00:22<00:00,  1.14cell/s]
Building task 'plot_pre_vs_post_retrofit_bers':  85%|▊| 11/13 [03:17<00:46, 23.1
Executing:   0%|                                       | 0/10 [00:00<?, ?cell/s]
Executing:  10%|███                            | 1/10 [00:03<00:32,  3.62s/cell]
Executing:  20%|██████▏                        | 2/10 [00:04<00:16,  2.06s/cell]
Executing:  40%|████████████▍                  | 4/10 [00:04<00:04,  1.25cell/s]
Executing:  60%|██████████████████▌            | 6/10 [00:04<00:01,  2.19cell/s]
Executing:  80%|████████████████████████▊      | 8/10 [00:14<00:04,  2.26s/cell]
Executing:  90%|███████████████████████████▉   | 9/10 [00:15<00:01,  1.86s/cell]
Executing: 100%|██████████████████████████████| 10/10 [00:16<00:00,  1.61s/cell]
Building task 'plot_pre_vs_post_retrofit_bers': 100%|█| 13/13 [03:34<00:00, 16.4
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/ploomber/cli/io.py", line 20, in wrapper
    fn(**kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/ploomber/cli/build.py", line 51, in main
    report = dag.build(force=args.force, debug=args.debug)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/ploomber/dag/dag.py", line 482, in build
    report = callable_()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/ploomber/dag/dag.py", line 581, in _build
    raise build_exception
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/ploomber/dag/dag.py", line 514, in _build
    show_progress=show_progress)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/ploomber/executors/serial.py", line 138, in __call__
    raise DAGBuildError(str(exceptions_all))
ploomber.exceptions.DAGBuildError: 
=============================== DAG build failed ===============================
- PythonCallable: download_small_area_boundaries -> File('data/external/dub..._routing_keys.gpkg') -
- /srv/conda/envs/notebook/lib/python3.7/site-packages/codema_dev_tasks/requests.py:8 -
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/implementations/http.py", line 394, in _info
    **kwargs,
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/implementations/http.py", line 753, in _file_info
    r.raise_for_status()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    headers=self.headers,
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://codema-dev.s3.eu-west-1.amazonaws.com/dublin_small_area_boundaries_in_routing_keys.gpkg')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/ploomber/tasks/abc.py", line 562, in _build
    res = self._run()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/ploomber/tasks/abc.py", line 669, in _run
    self.run()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/ploomber/tasks/tasks.py", line 124, in run
    out = self.source.primitive(**params)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/codema_dev_tasks/requests.py", line 34, in fetch_file
    with fsspec.open(url, "rb") as remote_file:
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/core.py", line 103, in __enter__
    f = self.fs.open(self.path, mode=mode)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/spec.py", line 1012, in open
    **kwargs,
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/implementations/http.py", line 349, in _open
    size = size or self.info(path, **kwargs)["size"]
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/asyn.py", line 91, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/asyn.py", line 71, in sync
    raise return_result
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/asyn.py", line 25, in _runner
    result[0] = await coro
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/fsspec/implementations/http.py", line 402, in _info
    raise FileNotFoundError(url) from exc
FileNotFoundError: https://codema-dev.s3.eu-west-1.amazonaws.com/dublin_small_area_boundaries_in_routing_keys.gpkg

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/multiprocessing/pool.py", line 121, in worker
    result = (True, func(*args, **kwds))
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/ploomber/tasks/abc.py", line 581, in _build
    raise TaskBuildError(msg) from e
ploomber.exceptions.TaskBuildError: Error building task "download_small_area_boundaries"
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/ploomber/executors/serial.py", line 186, in catch_exceptions
    fn()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/ploomber/executors/serial.py", line 159, in __call__
    return self.fn(**self.kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/ploomber/executors/serial.py", line 166, in catch_warnings
    result = fn()
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/ploomber/executors/serial.py", line 159, in __call__
    return self.fn(**self.kwargs)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/ploomber/executors/serial.py", line 220, in build_in_subprocess
    report, meta = res.get()
  File "/srv/conda/envs/notebook/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
ploomber.exceptions.TaskBuildError: Error building task "download_small_area_boundaries"
=============================== Summary (1 task) ===============================
PythonCallable: download_small_area_boundaries -> File('data/external/dub..._routing_keys.gpkg')
=============================== DAG build failed ===============================
```

**Comment by rdmolony** [comment]
This one's an easy fix though I wish it had a better error message 👀 

This means that the requested file `dublin_small_area_boundaries_in_routing_keys.gpkg` isn't found on s3, which would make sense as I did rename it by timestamping it and move it into view/
```
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://codema-dev.s3.eu-west-1.amazonaws.com/dublin_small_area_boundaries_in_routing_keys.gpkg')
```
